

POST http://localhost:5500/product
Content-Type: application/json

{
  "name": "New Product",
  "price": 99.99,
  "description": "A new product has been  added "
}

####

GET http://localhost:5500/product

####

GET http://localhost:5500/product

#####

GET http://localhost:5500/product

