

POST http://localhost:5500/product
Content-Type: application/json

{
  "name": "Smart Tv Hisense 60' ",
  "price": 99.99,
  "description": "A new product has been  added "
}

####

GET http://localhost:5500/product

####

GET http://localhost:5500/product

#####

GET http://localhost:5500/product

